---
- name: "<r_get_pkg_t_extract> create directory {{ deploy_root }}/install"
  file:
    path: "{{ deploy_root }}/install"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "<r_get_pkg_t_extract> extract /tmp/{{ package_tarball }} into {{ deploy_root }}/install/"
  unarchive:
    src: "/tmp/{{ package_tarball }}"
    dest: "{{ deploy_root }}/install/"
    #owner:
    #group:
    #mode:
    # If the specified absolute path (file or directory) already
    # exists, this step will *not* be run.
    #creates:
    list_files: yes
  register: unpack_result

- name: set variable archive_root
  set_fact:
    archive_root: "{{ unpack_result['files'][0] }}"

- name: "<r_get_pkg_t_extract> rename the file to {{ deploy_root }}/install/{{ package_fullname }}"
  command:
  #become: yes
  #become_method: su
  #become_user:
  #become_flags: "-s /bin/sh"
  args:
    cmd: "mv {{ archive_root }} {{ package_fullname }}"
    chdir: "{{ deploy_root }}/install"
    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *won't* be run.
    creates: "{{ package_fullname }}"

    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *will* be run.
    #remove:
